package br.ufes.informatica.doeLivros.libraries.domain;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
public class Library extends PersistentObjectSupport implements Comparable<Library> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. false */
	private String name;
	
	private String linkGoogleMaps;
	
	private Double latitude;

	private Double longitude;
	
	/** Getter for name. */
	public String getName() {
		return name;
	}

	/** Setter for name. */
	public void setName(String name) {
		this.name = name;
	}
	
	/** Getter for linkGoogleMaps. */
	public String getLinkGoogleMaps() {
		return linkGoogleMaps;
	}

	/** Setter for linkGoogleMaps. */
	public void setLinkGoogleMaps(String linkGoogleMaps) {
		this.linkGoogleMaps = linkGoogleMaps;
	}
	
	/** Getter for latitude. */
	public Double getLatitude() {
		return latitude;
	}

	/** Setter for latitude. */
	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}
	
	/** Getter for longitude. */
	public Double getLongitude() {
		return longitude;
	}

	/** Setter for longitude. */
	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Library o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}