package br.ufes.informatica.doeLivros.book.application;

import javax.ejb.Local;

import br.ufes.inf.nemo.jbutler.ejb.application.CrudService;
import br.ufes.informatica.doeLivros.book.domain.Book;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface BookRegistrationService extends CrudService<Book> {

	/** TODO: generated by FrameWeb. Should be documented. 
	public boolean insertBook(Book book);
	 */
}