package br.ufes.informatica.doeLivros.book.persistence;

import java.util.Date;
import java.util.List;

import javax.ejb.Local;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.doeLivros.book.domain.Book;
import br.ufes.informatica.doeLivros.people.domain.Person;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface BookDAO extends BaseDAO<Book> {

	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Book> getBookByTitle(String title);

	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Book> getBookByAuthor(String author);

	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Book> getBookList();

	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Book> getBookListWithParams(String author, String donorName, String genre, String title,
			Date availabilityDate, String editor, Integer publicationYear);

	public List<Book> getBookListByDonor(Person donatedBy);

}