package br.ufes.informatica.doeLivros.people.persistence;

import javax.ejb.Local;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.doeLivros.people.domain.Address;
import br.ufes.informatica.doeLivros.people.domain.Person;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface AddressDAO extends BaseDAO<Address> {

	/** TODO: generated by FrameWeb. Should be documented. */
	public String getPersonAddress(Person person);

}