package br.ufes.informatica.doeLivros.people.persistence;

import java.util.List;

import javax.ejb.Local;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.doeLivros.core.domain.User;
import br.ufes.informatica.doeLivros.people.domain.Person;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface PersonDAO extends BaseDAO<Person> {

	/** TODO: generated by FrameWeb. Should be documented. */
	public Person getPersonByUser(User user);

	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Person> getPersonList();

}