package br.ufes.informatica.doeLivros.core.persistence;

import java.util.List;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;
import javax.persistence.metamodel.EntityType;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseJPADAO;
import br.ufes.inf.nemo.jbutler.ejb.persistence.exceptions.MultiplePersistentObjectsFoundException;
import br.ufes.inf.nemo.jbutler.ejb.persistence.exceptions.PersistentObjectNotFoundException;
import br.ufes.informatica.doeLivros.core.domain.Role;
import br.ufes.informatica.doeLivros.core.domain.User;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class UserDAOJPA extends BaseJPADAO<User> implements UserDAO {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@PersistenceContext
	private EntityManager entityManager;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	protected EntityManager getEntityManager() {
		return entityManager;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public User getUserByEmail(String userEmail) throws PersistentObjectNotFoundException, MultiplePersistentObjectsFoundException {
		
	    CriteriaBuilder cb = entityManager.getCriteriaBuilder();
	    CriteriaQuery<User> cq = cb.createQuery(User.class);
	    Root<User> root = cq.from(User.class);

	    EntityType<User> model = root.getModel();
	    cq.where(cb.equal(root.get(model.getSingularAttribute("email")), userEmail));
	    User result = executeSingleResultQuery(cq, userEmail);
	    return result;
		// FIXME: auto-generated method stub
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public List<User> getUserList() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public List<User> getUserByRole(Role role) {
		// FIXME: auto-generated method stub
		return null;
	}
	
	public User merge(User user) {
		return entityManager.merge(user);
	}

}