package br.ufes.informatica.doeLivros.libraries.controller;

import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.inject.Model;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.doeLivros.libraries.application.PublicLibrariesSearchService;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class PublicLibrariesSearchController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private PublicLibrariesSearchService publicLibrariesSearchService;
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	private List librariesList;
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	public String callSearchAPI() {
		// FIXME: auto-generated method stub
		return null;
	}
	
	
	
	/** Getter for librariesList. */
	public List getLibrariesList() {
		return librariesList;
	}

	/** Setter for librariesList. */
	public void setLibrariesList(List librariesList) {
		this.librariesList = librariesList;
	}
	
}