package br.ufes.informatica.doeLivros.libraries.controller;

import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import org.apache.http.client.ClientProtocolException;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.doeLivros.libraries.application.PublicLibrariesSearchService;
import br.ufes.informatica.doeLivros.libraries.domain.Library;

/** TODO: generated by FrameWeb. Should be documented. */
@Named
@SessionScoped
public class PublicLibrariesSearchController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private PublicLibrariesSearchService publicLibrariesSearchService;

	/** TODO: generated by FrameWeb. Should be documented. */
	private List<Library> librariesList;
	
	public List<Library> getLibrariesList() throws ClientProtocolException {	
		
		this.librariesList = publicLibrariesSearchService.callSearchAPI(); 
		// FIXME: auto-generated method stub
		return this.librariesList;
	}
		
	/** Setter for librariesList. */
	public void setLibrariesList(List<Library> librariesList) {
		this.librariesList = librariesList;
	}

}