package br.ufes.informatica.doeLivros.people.domain;

import javax.persistence.Entity;
import javax.persistence.OneToOne;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Address extends PersistentObjectSupport implements Comparable<Address> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull @Size(max = 100) 
	private String country;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull @Size(max = 100) 
	private String province;

	/** TODO: generated by FrameWeb. Should be documented. false */
	 @Size(max = 100) 
	private String city;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull @Size(max = 15) 
	private String zipCode;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToOne(mappedBy="addressTarget")
		private Person personSource;
		
	




	/** Getter for country. */
	public String getCountry() {
		return country;
	}
	
	/** Setter for country. */
	public void setCountry(String country) {
		this.country = country;
	}

	/** Getter for province. */
	public String getProvince() {
		return province;
	}
	
	/** Setter for province. */
	public void setProvince(String province) {
		this.province = province;
	}

	/** Getter for city. */
	public String getCity() {
		return city;
	}
	
	/** Setter for city. */
	public void setCity(String city) {
		this.city = city;
	}

	/** Getter for zipCode. */
	public String getZipCode() {
		return zipCode;
	}
	
	/** Setter for zipCode. */
	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}




		
		/** Getter for Source. */
		public Person getSource() {
			return personSource;
		}
		
		/** Setter for Source. */
		public void setSource(Person Source) {
			this.personSource = Source;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Address o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}