package br.ufes.informatica.doeLivros.book.controller;

import java.util.Date;
import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.doeLivros.book.application.BookSearchService;
import br.ufes.informatica.doeLivros.book.domain.Book;

/** TODO: generated by FrameWeb. Should be documented. */
@Named
@SessionScoped
public class BookSearchController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private BookSearchService bookSearchService;

	/** TODO: generated by FrameWeb. Should be documented. */
	private List<Book> bookList;

	/** TODO: generated by FrameWeb. Should be documented. */
	private String title;

	/** TODO: generated by FrameWeb. Should be documented. */
	private String editor;

	/** TODO: generated by FrameWeb. Should be documented. */
	private Integer publicationYear;

	/** TODO: generated by FrameWeb. Should be documented. */
	private String genre;

	/** TODO: generated by FrameWeb. Should be documented. */
	private String donorName;

	/** TODO: generated by FrameWeb. Should be documented. */
	private Date availabilityDate;

	/** TODO: generated by FrameWeb. Should be documented. */
	private String author;

	/** TODO: generated by FrameWeb. Should be documented. */
	public String getBookListPage() {
		this.bookList = this.bookSearchService.getBookList(title, author, editor, publicationYear, genre, availabilityDate, donorName);
		return "index.xhtml?faces-redirect=true";
	}

	/** Getter for bookList. */
	public List<Book> getBookList() {
		return bookList;
	}

	/** Setter for bookList. */
	public void setBookList(List<Book> bookList) {
		this.bookList = bookList;
	}

	/** Getter for title. */
	public String getTitle() {
		return title;
	}

	/** Setter for title. */
	public void setTitle(String title) {
		this.title = title;
	}

	/** Getter for editor. */
	public String getEditor() {
		return editor;
	}

	/** Setter for editor. */
	public void setEditor(String editor) {
		this.editor = editor;
	}

	/** Getter for publicationYear. */
	public Integer getPublicationYear() {
		return publicationYear;
	}

	/** Setter for publicationYear. */
	public void setPublicationYear(Integer publicationYear) {
		this.publicationYear = publicationYear;
	}

	/** Getter for genre. */
	public String getGenre() {
		return genre;
	}

	/** Setter for genre. */
	public void setGenre(String genre) {
		this.genre = genre;
	}

	/** Getter for donorName. */
	public String getDonorName() {
		return donorName;
	}

	/** Setter for donorName. */
	public void setDonorName(String donorName) {
		this.donorName = donorName;
	}

	/** Getter for availabilityDate. */
	public Date getAvailabilityDate() {
		return availabilityDate;
	}

	/** Setter for availabilityDate. */
	public void setAvailabilityDate(Date availabilityDate) {
		this.availabilityDate = availabilityDate;
	}

	/** Getter for author. */
	public String getAuthor() {
		return author;
	}

	/** Setter for author. */
	public void setAuthor(String author) {
		this.author = author;
	}

}