package br.ufes.informatica.doeLivros.book.controller;

import javax.ejb.EJB;
import javax.enterprise.inject.Model;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.doeLivros.book.application.BookRegistrationService;
import br.ufes.informatica.doeLivros.book.domain.Book;
import br.ufes.informatica.doeLivros.core.domain.User;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class BookRegistrationController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private BookRegistrationService bookRegistrationService;
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	private Book book;
	
	/** TODO: generated by FrameWeb. Should be documented. */
	private User currentUser;
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	public String insertBook() {
		// FIXME: auto-generated method stub
		return null;
	}
	
	
	
	/** Getter for book. */
	public Book getBook() {
		return book;
	}

	/** Setter for book. */
	public void setBook(Book book) {
		this.book = book;
	}
	
	/** Getter for currentUser. */
	public User getCurrentUser() {
		return currentUser;
	}

	/** Setter for currentUser. */
	public void setCurrentUser(User currentUser) {
		this.currentUser = currentUser;
	}
	
}