package br.ufes.informatica.doeLivros.book.controller;

import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.inject.Model;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.doeLivros.book.application.BookSearchService;
import br.ufes.informatica.doeLivros.book.domain.Book;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class BookSearchController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private BookSearchService bookSearchService;
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	private List<Book> bookList;
	
	/** TODO: generated by FrameWeb. Should be documented. */
	private Book book;
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	public String getBookList1() {
		// FIXME: auto-generated method stub
		return null;
	}
	
	
	
	/** Getter for bookList. */
	public List<Book> getBookList() {
		return bookList;
	}

	/** Setter for bookList. */
	public void setBookList(List<Book> bookList) {
		this.bookList = bookList;
	}
	
	/** Getter for book. */
	public Book getBook() {
		return book;
	}

	/** Setter for book. */
	public void setBook(Book book) {
		this.book = book;
	}
	
}