package br.ufes.informatica.doeLivros.book.controller;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import br.ufes.inf.nemo.jbutler.ejb.application.CrudService;
import br.ufes.inf.nemo.jbutler.ejb.controller.CrudController;
import br.ufes.informatica.doeLivros.book.application.BookRegistrationService;
import br.ufes.informatica.doeLivros.book.domain.Book;

/** TODO: generated by FrameWeb. Should be documented. */
@Named @SessionScoped 
public class BookRegistrationController extends CrudController<Book> {
	
	private static final long serialVersionUID = 1L;
	
	//private Person person;

	@EJB
	private BookRegistrationService bookRegistrationService;

	@Override
	protected CrudService<Book> getCrudService() {
		return bookRegistrationService;
	}

	@Override
	protected void initFilters() { }
	
	@Override
	protected void prepEntity() {
		System.out.println("ppassei aqui");
	}
	
	/*Working with the session
	protected void doGetSession(HttpServletRequest request, HttpServletResponse response)
	        throws ServletException, IOException {
	    HttpSession session = request.getSession();
	    
	    session.setAttribute("username", "Jordana Reis");
	    session.setAttribute("userId", "1");
	     
	    // work with the session...
	}
	
	//Working with the session
		protected void doGetSessionUser(HttpServletRequest request, HttpServletResponse response)
		        throws ServletException, IOException {
		    HttpSession session = request.getSession();
		    
		    String username = (String) session.getAttribute("username");   
		    Integer userId = (Integer) session.getAttribute("userId");
		     
		    // work with the session...
		}
	*/
}