package br.ufes.informatica.doeLivros.book.application;

import java.io.Serializable;

import javax.ejb.Local;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface BookSearchService extends Serializable {
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public void getBookList();
	
}