package br.ufes.informatica.doeLivros.book.application;

import java.util.Date;
import java.util.List;

import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.ufes.informatica.doeLivros.book.domain.Book;
import br.ufes.informatica.doeLivros.book.persistence.BookDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class BookSearchServiceBean implements BookSearchService {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private BookDAO bookDAO;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public List<Book> getBookList(String title, String author, String editor, int publicationYear, String genre,
			Date availabilityDate, String donorName) {
		// FIXME: auto-generated method stub
		return null;
	}

}