package br.ufes.informatica.doeLivros.book.application;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.ejb.Local;

import br.ufes.informatica.doeLivros.book.domain.Book;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface BookSearchService extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Book> getBookList(String title, String author, String editor, int publicationYear, String genre,
			Date availabilityDate, String donorName);

}