package br.ufes.informatica.doeLivros.book.application;

import java.io.Serializable;

import javax.ejb.Local;

import br.ufes.informatica.doeLivros.book.domain.Book;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface BookRegistrationService extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. */
	public boolean insertBook(Book book);

}