package br.ufes.informatica.doeLivros.core.controller;

import javax.ejb.EJB;
import javax.enterprise.inject.Model;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.doeLivros.core.application.AuthenticateService;
import br.ufes.informatica.doeLivros.core.domain.User;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class AuthenticateController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private AuthenticateService authenticateService;

	/** TODO: generated by FrameWeb. Should be documented. */
	private String email;

	/** TODO: generated by FrameWeb. Should be documented. */
	private String password;

	/** TODO: generated by FrameWeb. Should be documented. */
	private User user;

	/** TODO: generated by FrameWeb. Should be documented. */
	public String validate() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** Getter for email. */
	public String getEmail() {
		return email;
	}

	/** Setter for email. */
	public void setEmail(String email) {
		this.email = email;
	}

	/** Getter for password. */
	public String getPassword() {
		return password;
	}

	/** Setter for password. */
	public void setPassword(String password) {
		this.password = password;
	}

	/** Getter for user. */
	public User getUser() {
		return user;
	}

	/** Setter for user. */
	public void setUser(User user) {
		this.user = user;
	}

}