package br.ufes.informatica.doeLivros.core.controller;

import javax.ejb.EJB;
import javax.enterprise.inject.Model;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.doeLivros.core.application.RegisterService;
import br.ufes.informatica.doeLivros.core.domain.User;
import br.ufes.informatica.doeLivros.core.exceptions.EmailInUseException;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class RegisterController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private RegisterService registerService;

	/** TODO: generated by FrameWeb. Should be documented. */
	private User user = new User();

	/** TODO: generated by FrameWeb. Should be documented. */
	private String confirmPassword;

	/** TODO: generated by FrameWeb. Should be documented. */
	public String register() {
		// FIXME: auto-generated method stub
		if (confirmPassword.equals(user.getPassword())) {
			try {
				registerService.register(user);
			    } catch (EmailInUseException e) {
			      FacesContext.getCurrentInstance().addMessage(null,
			               new FacesMessage(FacesMessage.SEVERITY_ERROR, "Esse email já está registrado", ""));
			      return null;
			    }
			
		} else {
			FacesContext.getCurrentInstance().addMessage(null,
	                new FacesMessage(FacesMessage.SEVERITY_ERROR, "As senhas digitadas não correspondem", ""));
			return null;
		}
		return "/index.xhtml?faces-redirect=true";
	}

	/** Getter for user. */
	public User getUser() {
		return user;
	}

	/** Setter for user. */
	public void setUser(User user) {
		this.user = user;
	}

	/** Getter for confirmPassword. */
	public String getConfirmPassword() {
		return confirmPassword;
	}

	/** Setter for confirmPassword. */
	public void setConfirmPassword(String confirmPassword) {
		this.confirmPassword = confirmPassword;
	}

}