package br.ufes.informatica.doeLivros.core.domain;

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Permission extends PersistentObjectSupport implements Comparable<Permission> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	@Size(max = 100)
	private String name;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToMany(mappedBy = "permissionList")
	private Set<Role> rolesList;

	/** Getter for name. */
	public String getName() {
		return name;
	}

	/** Setter for name. */
	public void setName(String name) {
		this.name = name;
	}

	/** Getter for rolesList. */
	public Set<Role> getRolesList() {
		return rolesList;
	}

	/** Setter for rolesList. */
	public void setRolesList(Set<Role> rolesList) {
		this.rolesList = rolesList;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Permission o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}