package br.ufes.informatica.doeLivros.core.domain;

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Role extends PersistentObjectSupport implements Comparable<Role> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	@Size(max = 200)
	private String name;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToMany(mappedBy = "rolesList")
	private Set<User> userList;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToMany
	private Set<Permission> permissionList;
	
	public static final String ADMIN_ROLE_NAME = "Admin";

	public static final String USER_ROLE_NAME = "User";

	/** Getter for name. */
	public String getName() {
		return name;
	}

	/** Setter for name. */
	public void setName(String name) {
		this.name = name;
	}

	/** Getter for userList. */
	public Set<User> getUserList() {
		return userList;
	}

	/** Setter for userList. */
	public void setUserList(Set<User> userList) {
		this.userList = userList;
	}

	/** Getter for permissionList. */
	public Set<Permission> getPermissionList() {
		return permissionList;
	}

	/** Setter for permissionList. */
	public void setPermissionList(Set<Permission> permissionList) {
		this.permissionList = permissionList;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Role o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}