package br.ufes.informatica.doeLivros.core.domain;

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import javax.persistence.OneToOne;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;
import br.ufes.informatica.doeLivros.people.domain.Person;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class User extends PersistentObjectSupport implements Comparable<User> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	  
	private String nickname;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull @Size(max = 150) 
	private String email;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull @Size(max = 10) 
	private Character password;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToOne
		private Person userTarget;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToMany
		private Set<Role> roleTarget;
		
	




	/** Getter for nickname. */
	public String getNickname() {
		return nickname;
	}
	
	/** Setter for nickname. */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/** Getter for email. */
	public String getEmail() {
		return email;
	}
	
	/** Setter for email. */
	public void setEmail(String email) {
		this.email = email;
	}

	/** Getter for password. */
	public Character getPassword() {
		return password;
	}
	
	/** Setter for password. */
	public void setPassword(Character password) {
		this.password = password;
	}




		
		/** Getter for Target. */
		public Person getTarget() {
			return userTarget;
		}
		
		/** Setter for Target. */
		public void setTarget(Person userTarget) {
			this.userTarget = userTarget;
		}
		
	

		
		/** Getter for Target. */
		public Set<Role> getTargetRole() {
			return roleTarget;
		}
		
		/** Setter for Target. */
		public void setTarget(Set<Role> Target) {
			this.roleTarget = Target;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(User o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}