package br.ufes.informatica.doeLivros.libraries.application;

import java.io.Serializable;
import java.util.List;

import javax.ejb.Local;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface PublicLibrariesSearchService extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. */
	public List<String> callSearchAPI();

}