package br.ufes.informatica.doeLivros.libraries.application;

import javax.ejb.Stateless;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class PublicLibrariesSearchServiceBean implements PublicLibrariesSearchService {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;
	
	
	
	

	
	
	
}