package br.ufes.informatica.doeLivros.libraries.application;

import java.io.Serializable;

import javax.ejb.Local;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface PublicLibrariesSearchService extends Serializable {
	
}