package br.ufes.informatica.doeLivros.libraries.application;

import java.io.Serializable;
import java.util.List;

import javax.ejb.Local;

import org.apache.http.client.ClientProtocolException;

import br.ufes.informatica.doeLivros.libraries.domain.Library;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface PublicLibrariesSearchService extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. 
	 * @throws ClientProtocolException */
	public List<Library> callSearchAPI() throws ClientProtocolException;
	

}