package br.ufes.informatica.doeLivros.core.application;

import java.io.Serializable;

import javax.ejb.Local;

import br.ufes.informatica.doeLivros.core.domain.User;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface AuthenticateService extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. */
	public User authenticate(String email, String password);

	
}