package br.ufes.informatica.doeLivros.core.application;

import java.io.Serializable;

import javax.ejb.Local;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface AuthenticateService extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. */
	public void authenticate(String email, String password);

}