package br.ufes.informatica.doeLivros.core.application;

import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.ufes.informatica.doeLivros.core.domain.User;
import br.ufes.informatica.doeLivros.core.persistence.UserDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class RegisterServiceBean implements RegisterService {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private UserDAO userDAO;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void register(User user) {
		// FIXME: auto-generated method stub
		return;
	}

}
