package br.ufes.informatica.doeLivros.core.application;

import java.io.Serializable;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;

import javax.ejb.Local;

import br.ufes.informatica.doeLivros.core.domain.User;
import br.ufes.informatica.doeLivros.core.exceptions.EmailInUseException;
import br.ufes.informatica.doeLivros.core.exceptions.EncodeFailedException;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface RegisterService extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. */
	public void register(User user) throws EmailInUseException,  EncodeFailedException;
	
	public void checkAdminCreated() throws NoSuchAlgorithmException, UnsupportedEncodingException, EncodeFailedException;
	
	public User updateUser(User user);

}